const fs = require('fs');
const path = require('path');

const koPath = path.join(__dirname, '../messages/ko.json');
const koData = JSON.parse(fs.readFileSync(koPath, 'utf8'));

// Core translations mapping
const translations = {
  common: {
    approve: "승인",
    reject: "거절",
    enabled: "활성화됨",
    disabled: "비활성화됨",
    appName: "Shop Ship LTD",
    email: "이메일",
    language: "언어",
    english: "English",
    arabic: "العربية",
    korean: "한국어",
    loading: "로딩 중...",
    error: "오류",
    success: "성공",
    warning: "경고",
    info: "정보",
    close: "닫기",
    cancel: "취소",
    save: "저장",
    delete: "삭제",
    edit: "수정",
    view: "보기",
    back: "뒤로",
    next: "다음",
    previous: "이전",
    prev: "이전",
    submit: "제출",
    logout: "로그아웃",
    profile: "프로필",
    settings: "설정",
    help: "도움말",
    about: "소개",
    contact: "문의하기",
    noImage: "이미지 없음",
    share: "공유",
    linkCopied: "링크가 클립보드에 복사되었습니다",
    free: "무료",
    download: "인보이스 다운로드",
    merchant: "판매자",
    user: "사용자",
    follow: "팔로우",
    unfollow: "팔로우 취소",
    actions: "작업",
    date: "날짜",
    amount: "금액",
    viewAll: "전체 보기",
    viewResults: "결과 보기",
    all: "전체",
    saveAll: "모두 저장",
    page: "페이지",
    of: "/",
    name: "이름",
    role: "역할",
    status: "상태",
    items: "개 상품",
    item: "개 상품",
    live: "라이브",
    backToHome: "홈으로 돌아가기",
    change: "변경",
    na: "해당 없음",
    phone: "전화번호",
    remove: "제거",
    search: "검색",
    submitted: "제출됨",
    clickToUpload: "클릭하여 업로드",
    confirm: "확인",
    file: "파일",
    fileSelected: "선택된 파일",
    submitting: "제출 중...",
    deleting: "삭제 중...",
    home: "홈",
    ratings: "평점",
    chat: "채팅",
    contactSupport: "고객 지원 문의",
    submitReview: "리뷰 제출",
    products: "상품",
    sales: "판매",
    followers: "팔로워",
    visitStore: "스토어 방문",
    processing: "처리 중...",
    color: "색상",
    size: "사이즈",
    brandPart1: "Shop",
    brandPart2: "& Ship",
    brandPart3: " LTD",
    option: "옵션",
    saving: "저장 중...",
    noOrdersFound: "주문 내역이 없습니다",
    adjustFilters: "필터를 조정해 보세요",
    orderNotFound: "주문을 찾을 수 없습니다",
    goToImage: "이미지로 이동",
    errorOccurred: "오류가 발생했습니다"
  },
  nav: {
    categories: "카테고리",
    about: "소개",
    contact: "문의",
    home: "홈",
    products: "상품",
    merchants: "판매자",
    cart: "장바구니",
    wishlist: "위시리스트",
    orders: "주문",
    dashboard: "대시보드",
    search: "상품 검색...",
    menu: "메뉴",
    notifications: "알림",
    becomeMerchant: "판매자 등록",
    switchToMerchant: "판매자 전환",
    goToDashboard: "내 대시보드로 이동",
    account: "계정",
    signup: "회원가입",
    signin: "로그인",
    settings: "설정",
    whyChoose: "왜 선택해야 할까요? ",
    brandName: "Shop Ship LTD?",
    quickLink1: "신상품",
    quickLink2: "베스트셀러",
    quickLink3: "인기 상품",
    quickLink4: "최대 할인",
    searchBtn: "검색",
    myWallet: "내 지갑",
    trust1: "빠른 배송",
    trust2: "90일 이내 간편 반품",
    trust3: "안전한 결제",
    trust4: "10,000+ 인증됨",
    trust5: "전 세계 배송",
    trust6: "24/7 전담 고객 지원",
    trust7: "정품 보장",
    trust8: "최저가 보장",
    searchHistory: "검색 기록",
    security: "보안",
    customerService: "고객 서비스",
    more: "더 보기",
    explore: "둘러보기",
    logout: "로그아웃",
    filter: {
      category: "카테고리"
    },
    common: {
      close: "닫기",
      somethingWentWrong: "문제가 발생했습니다",
      errorOccurred: "예기치 않은 오류가 발생했습니다. 페이지를 새로고침하거나 문제가 지속되면 고객 지원에 문의하십시오.",
      refreshPage: "페이지 새로고침",
      goBack: "뒤로 가기",
      active: "활성",
      inactive: "비활성",
      noOrdersFound: "주문 내역이 없습니다",
      adjustFilters: "필터를 조정해 보세요",
      orderNotFound: "주문을 찾을 수 없습니다",
      officialInvoice: "공식 인보이스",
      namePlaceholder: "홍길동",
      emailPlaceholder: "hong@example.com",
      addressPlaceholder: "서울시 강남구...",
      cityPlaceholder: "서울",
      provincePlaceholder: "경기도",
      countryPlaceholder: "대한민국",
      merchant: "판매자",
      user: "사용자",
      amount: "금액",
      date: "날짜",
      actions: "작업",
      na: "해당 없음",
      page: "페이지",
      of: "/",
      brandPart1: "Shop",
      brandPart2: "& Ship",
      brandPart3: " LTD"
    }
  },
  home: {
    heroTitle: "Shop Ship LTD에 오신 것을 환영합니다",
    heroSubtitle: "프리미엄 제품을 위한 완벽한 드롭쉬핑 플랫폼. 신뢰할 수 있는 판매자의 수천 가지 제품을 둘러보세요.",
    flashDealsSubtitle: "한정 기간 딜",
    flashDealsTitle: "반짝 세일 — 최대 50% 할인",
    flashDealsDesc: "일부 선정된 제품. 오늘 하루만!",
    shopNow: "지금 쇼핑하기",
    browseProducts: "상품 둘러보기",
    getStarted: "시작하기",
    whyChooseUs: "왜 Shop Ship LTD일까요?",
    productsCount: "1000+ 상품",
    productsDesc: "고품질 제품의 다양한 선택",
    merchantsCount: "100+ 판매자",
    merchantsDesc: "검증된 리뷰를 가진 신뢰할 수 있는 판매자",
    supportCount: "24/7 지원",
    supportDesc: "언제나 여러분의 성공을 돕기 위해 대기 중입니다",
    featuredProducts: "추천 상품",
    featuredDesc: "가장 인기 있는 상품을 확인해 보세요",
    viewAll: "전체 보기",
    viewAllProducts: "모든 상품 보기",
    viewAllOrders: "모든 주문 보기",
    readyToStart: "쇼핑을 시작할 준비가 되셨나요?",
    readyDesc: "고품질 제품을 구매하는 수천 명의 고객과 함께하세요",
    signupNow: "지금 회원가입하기",
    newArrivals: "신상품",
    newArrivalsDesc: "방금 도착한 따끈따끈한 신상품을 만나보세요",
    viewAllNew: "모든 신상품 보기",
    topRated: "인기 상품",
    topRatedDesc: "고객이 선호하는 최고의 상품",
    viewAllTopRated: "모든 인기 상품 보기",
    biggestDiscounts: "최대 할인",
    biggestDiscountsDesc: "최고의 딜과 경쟁력 있는 가격을 만나보세요",
    viewAllDiscounts: "모든 할인 상품 보기",
    notFoundDesc: "최고의 공급업체가 제공하는 수백 가지 제품의 전체 카탈로그를 둘러보세요.",
    browseAllProducts: "모든 상품 둘러보기",
    topMerchants: "최우수 판매자",
    topMerchantsDesc: "최고 품질의 제품을 제공하는 검증된 파트너",
    noProducts: "등록된 상품이 없습니다",
    noMerchants: "검증된 판매자가 없습니다",
    notFoundTitle: "상품을 찾을 수 없습니다",
    categories: {
      all: "전체",
      strips: "일반",
      panels: "전자제품",
      smart: "스마트 기기",
      neon: "홈 데코",
      outdoor: "아웃도어",
      essentials: "필수품",
      controllers: "컨트롤러",
      accessories: "액세서리"
    }
  },
  notFound: {
    title: "404 - 페이지를 찾을 수 없습니다",
    description: "죄송합니다! 요청하신 페이지가 존재하지 않거나 이동되었습니다.",
    goBack: "뒤로 가기",
    goHome: "홈으로 돌아가기",
    browseProducts: "상품 둘러보기"
  }
};

// Merge translations
Object.keys(translations).forEach(namespace => {
  koData[namespace] = {
    ...koData[namespace],
    ...translations[namespace]
  };
});

fs.writeFileSync(koPath, JSON.stringify(koData, null, 2), 'utf8');
console.log('Successfully updated core Korean translations in ko.json');
